### ISSUE TITLE
site not working

### ISSUE THREAD

**Issue by Pratiknarola** [pirateksh/piratetube#1]
I just visited your github.io site and I waited for more than half an hour but it only shows Loading. I don't know if it is taking too long to load all data of youtube or your servers are down but If you could somehow start your site again, it would be really great and also I can't see any button to click search. and if you have implemented hit enter to search then it is not working either.

**Comment by pirateksh** [comment]
It's "Search as you type" in the Search tab. Site will not work for the day if daily limit of fetching data using Youtube API is exhausted.
